AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mortgage-calculator

  Sample SAM Template for mortgage-calculator

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  MortgageCalculatorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: MortgageCalculatorFunction
      Handler: mortgagecalculator.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        MortgageCalculator:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /calculate
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MortgageCalculatorFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for MortgageCalculator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calculate/"
  MortgageCalculatorFunction:
    Description: "MortgageCalculator Lambda Function ARN"
    Value: !GetAtt MortgageCalculatorFunction.Arn
  MortgageCalculatorFunctionIamRole:
    Description: "Implicit IAM Role created for MortgageCalculator function"
    Value: !GetAtt MortgageCalculatorFunctionRole.Arn
